In [5]:
import sys
sys.path.append('../')
from utility.file_utility import FileUtility
import pandas as pd
import numpy as np
from sklearn.metrics.classification import precision_recall_fscore_support
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import f1_score

In [2]:
files_cv=FileUtility.recursive_glob('/mounts/data/proj/asgari/res/','*.pickle')


In [ ]:
def load_res(file):
    [label_set, conf, best_score_, best_estimator_,
                              cv_results_, best_params_,  (y_predicted, Y,label_set ), (Y_test_pred, Y_test) ]=FileUtility.load_obj(file)
    
    

In [23]:
for file in files_cv:
    [label_set, conf, best_score_, best_estimator_,
                              cv_results_, best_params_,  (y_predicted, Y,label_set ), (Y_test_pred, Y_test) ]=FileUtility.load_obj(file)
    (ptest0,ptest1),(rtest0,rtest1),(f1test0,f1test1),_=precision_recall_fscore_support(Y_test,Y_test_pred)
    (ptrain0,ptrain1),(rtrain0,rtrain1),(f1train0,f1train1),_=precision_recall_fscore_support(Y,y_predicted)
    print (f1train1)
    print (f1train0)
    print (f1test1)
    print (f1test0)

1.0
1.0
0.9032258064516129
0.4
0.9218106995884774
0.7466666666666667
0.9655172413793104
0.8571428571428571
1.0
1.0
0.8750000000000001
0.0
1.0
1.0
0.8750000000000001
0.0
0.996078431372549
0.9841269841269841
0.8750000000000001
0.0
1.0
1.0
0.9655172413793104
0.8571428571428571
1.0
1.0
0.7586206896551724
0.0
1.0
1.0
0.8750000000000001
0.0
0.996078431372549
0.9841269841269841
0.8750000000000001
0.0
0.9262295081967213
0.7567567567567567
0.9655172413793104
0.8571428571428571
1.0
1.0
0.8750000000000001
0.0
1.0
1.0
0.7586206896551724
0.0


/mounts/Users/student/asgari/.local/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/mounts/Users/student/asgari/.local/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LinearSVC from version 0.19.0 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/mounts/Users/student/asgari/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/mounts/Users/student/asgari/.local/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.19.0 wh

In [24]:
cv_results_

{'mean_fit_time': array([2.47856293, 1.97495112, 0.14051986, 0.13648925, 1.92720113,
        1.69194319, 0.12766435, 0.12591093, 1.92505627, 1.74933777,
        0.12773426, 0.13041332, 2.0388942 , 1.52486393, 0.12313054,
        0.12010927, 1.88670726, 1.5409368 , 0.13099329, 0.12505052,
        1.92873616, 1.7767163 , 0.12000358, 0.12739687, 2.20990057,
        1.57143998, 0.12288799, 0.12806296, 1.83563776, 1.38094227,
        0.12892871, 0.12645056, 1.94075687, 1.54799459, 0.13207984,
        0.12174826, 1.90642571, 1.4958307 , 0.12219422, 0.12331364,
        2.08694224, 1.45829754, 0.12839217, 0.11683877, 1.55008185,
        1.45595133, 0.12082236, 0.12405274, 1.67026477, 1.47677724,
        0.13246746, 0.1221946 , 1.76693516, 1.27327466, 0.12004364,
        0.11506515, 1.7240948 , 1.29471688, 0.1244004 , 0.12496607,
        1.7381418 , 1.29845424, 0.11938055, 0.11897504, 1.72585623,
        1.25914161, 0.12875936, 0.11658356, 1.61228116, 1.16505609,
        0.12402291, 0.12596292,

In [16]:
f1test0

array([0.        , 0.75862069])

In [17]:
rtest1

array([0.        , 0.78571429])

In [18]:
f1train1

array([1., 1.])

In [19]:
f1train0

array([1., 1.])