In [45]:
import sys
sys.path.append('../')
from utility.file_utility import FileUtility
import pandas as pd
import numpy as np
from sklearn.metrics.classification import precision_recall_fscore_support
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

In [50]:
files_cv=FileUtility.recursive_glob('/mounts/data/proj/asgari/res/','*.pickle')

files_cv.sort()
table_test = {'classifier': [], 'feature': [], 'CV':[],'Precision':[],'Recall':[],'F1':[],'accuracy':[]}
table_cv = {'classifier': [], 'feature': [], 'CV':[],'Precision':[],'Recall':[],'F1':[],'accuracy':[]}

import warnings
warnings.filterwarnings('ignore')

for file in files_cv:
    [label_set, conf, label_set, best_score_, best_estimator_,
                              cv_results_, best_params_,  (cv_predictions_pred,cv_predictions_trues ), (Y_test_pred, Y_test) ]=FileUtility.load_obj(file)
    rep=file.split('/')[-1].split('_CV_')[0]
    CV_scheme=file.split('_CV_')[1].split('_')[0]
    classifier=file.split('_CV_')[1].split('_')[1].split('.')[0]
    
    table_test['feature'].append(rep)
    table_test['classifier'].append(classifier)
    table_test['CV'].append(CV_scheme)
    table_test['Precision'].append(np.round(precision_score(Y_test,Y_test_pred),2))
    table_test['Recall'].append(np.round(recall_score(Y_test,Y_test_pred),2))
    table_test['F1'].append(np.round(f1_score(Y_test,Y_test_pred),2))
    table_test['accuracy'].append(np.round(accuracy_score(Y_test,Y_test_pred),2))
    
    table_cv['feature'].append(rep)
    table_cv['classifier'].append(classifier)
    table_cv['CV'].append(CV_scheme)
    table_cv['Precision'].append(np.round(precision_score(cv_predictions_trues,cv_predictions_pred),2))
    table_cv['Recall'].append(np.round(recall_score(cv_predictions_trues,cv_predictions_pred),2))
    table_cv['F1'].append(np.round(f1_score(cv_predictions_trues,cv_predictions_pred),2))
    table_cv['accuracy'].append(np.round(accuracy_score(cv_predictions_trues,cv_predictions_pred),2))
    df1=pd.DataFrame(data=table_test,columns=['feature', 'CV','classifier','accuracy','Precision','Recall','F1'])
    df2=pd.DataFrame(data=table_cv,columns=['feature', 'CV','classifier','accuracy','Precision','Recall','F1'])
    
writer = pd.ExcelWriter('results.xlsx')
df1.to_excel(writer,'Test')
df2.to_excel(writer,'Cross-validation')
writer.save()

In [43]:
df1

feature    CV  classifier  accuracy  \
0            kpneumoniae_gpauniq  rand   LR.pickle  0.666667   
1            kpneumoniae_gpauniq  rand   RF.pickle  0.777778   
2            kpneumoniae_gpauniq  rand  SVM.pickle  0.722222   
3   kpneumoniae_non-syn_SNPsuniq  rand   LR.pickle  0.666667   
4   kpneumoniae_non-syn_SNPsuniq  rand   RF.pickle  0.777778   
5   kpneumoniae_non-syn_SNPsuniq  rand  SVM.pickle  0.666667   
6       kpneumoniae_syn_SNPsuniq  rand   LR.pickle  0.722222   
7       kpneumoniae_syn_SNPsuniq  rand   RF.pickle  0.777778   
8       kpneumoniae_syn_SNPsuniq  rand  SVM.pickle  0.722222   
9                  sequence_6mer  rand   LR.pickle  0.944444   
10                 sequence_6mer  rand   RF.pickle  0.944444   
11                 sequence_6mer  rand  SVM.pickle  0.944444   

    Precision_class1  Recall_class1  F1_class1  Precision_class0  \
0           0.750000       0.857143   0.800000          0.000000   
1           0.777778       1.000000   0.875000          0.000000   
2           0.764706       0.928571   0.838710          0.000000   
3           0.785714       0.785714   0.785714          0.250000   
4           0.777778       1.000000   0.875000          0.000000   
5           0.785714       0.785714   0.785714          0.250000   
6           0.800000       0.857143   0.827586          0.333333   
7           0.777778       1.000000   0.875000          0.000000   
8           0.800000       0.857143   0.827586          0.333333   
9           0.933333       1.000000   0.965517          1.000000   
10          0.933333       1.000000   0.965517          1.000000   
11          0.933333       1.000000   0.965517          1.000000   

    Recall_class0  F1_class0  
0            0.00   0.000000  
1            0.00   0.000000  
2            0.00   0.000000  
3            0.25   0.250000  
4            0.00   0.000000  
5            0.25   0.250000  
6            0.25   0.285714  
7            0.00   0.000000  
8            0.25   0.285714  
9            0.75   0.857143  
10           0.75   0.857143  
11           0.75   0.857143

In [44]:
df2

feature    CV  classifier  accuracy  \
0            kpneumoniae_gpauniq  rand   LR.pickle  0.765517   
1            kpneumoniae_gpauniq  rand   RF.pickle  0.779310   
2            kpneumoniae_gpauniq  rand  SVM.pickle  0.710345   
3   kpneumoniae_non-syn_SNPsuniq  rand   LR.pickle  0.717241   
4   kpneumoniae_non-syn_SNPsuniq  rand   RF.pickle  0.772414   
5   kpneumoniae_non-syn_SNPsuniq  rand  SVM.pickle  0.682759   
6       kpneumoniae_syn_SNPsuniq  rand   LR.pickle  0.751724   
7       kpneumoniae_syn_SNPsuniq  rand   RF.pickle  0.744828   
8       kpneumoniae_syn_SNPsuniq  rand  SVM.pickle  0.737931   
9                  sequence_6mer  rand   LR.pickle  0.848276   
10                 sequence_6mer  rand   RF.pickle  0.772414   
11                 sequence_6mer  rand  SVM.pickle  0.868966   

    Precision_class1  Recall_class1  F1_class1  Precision_class0  \
0           0.811024       0.911504   0.858333          0.444444   
1           0.787234       0.982301   0.874016          0.500000   
2           0.793388       0.849558   0.820513          0.291667   
3           0.815789       0.823009   0.819383          0.354839   
4           0.781690       0.982301   0.870588          0.333333   
5           0.801802       0.787611   0.794643          0.294118   
6           0.793893       0.920354   0.852459          0.357143   
7           0.771429       0.955752   0.853755          0.000000   
8           0.786260       0.911504   0.844262          0.285714   
9           0.950495       0.849558   0.897196          0.613636   
10          0.827869       0.893805   0.859574          0.478261   
11          0.960784       0.867257   0.911628          0.651163   

    Recall_class0  F1_class0  
0         0.25000   0.320000  
1         0.06250   0.111111  
2         0.21875   0.250000  
3         0.34375   0.349206  
4         0.03125   0.057143  
5         0.31250   0.303030  
6         0.15625   0.217391  
7         0.00000   0.000000  
8         0.12500   0.173913  
9         0.84375   0.710526  
10        0.34375   0.400000  
11        0.87500   0.746667

In [52]:
import pandas as pd
import itertools
from Bio import Phylo

ifile = sys.argv[1]

t = Phylo.read('../data_config/mitip_422_gt90.fasttree', 'newick')

d = {}
for x, y in itertools.combinations(t.get_terminals(), 2):
    v = t.distance(x, y)
    d[x.name] = d.get(x.name, {})
    d[x.name][y.name] = v
    d[y.name] = d.get(y.name, {})
    d[y.name][x.name] = v
for x in t.get_terminals():
    d[x.name][x.name] = 0

m = pd.DataFrame(d)

In [62]:
isolates=[x for x in m.axes[0]]
isolates.sort()

In [64]:
mat=np.zeros((len(isolates),len(isolates)))
for x in range(len(isolates)):
    for y in range(len(isolates)):
        mat[x,y]=m[isolates[x]][isolates[y]]

In [66]:
mat

array([[0.        , 0.26148641, 0.16265087, ..., 0.1653693 , 0.27532354,
        0.27498143],
       [0.26148641, 0.        , 0.23436995, ..., 0.23708838, 0.15012485,
        0.14978273],
       [0.16265087, 0.23436995, 0.        , ..., 0.07828251, 0.24820707,
        0.24786496],
       ...,
       [0.1653693 , 0.23708838, 0.07828251, ..., 0.        , 0.2509255 ,
        0.25058339],
       [0.27532354, 0.15012485, 0.24820707, ..., 0.2509255 , 0.        ,
        0.00224241],
       [0.27498143, 0.14978273, 0.24786496, ..., 0.25058339, 0.00224241,
        0.        ]])

In [72]:

from sklearn.cluster import SpectralClustering


In [89]:
clustering = SpectralClustering(n_clusters=20,assign_labels="kmeans",random_state=0).fit(np.exp(- mat ** 2 / (2. * 0.08 ** 2))
)

In [90]:
clustering.labels_

array([ 7, 12,  4, 16,  1, 10,  3,  3,  8,  3, 16,  1,  3,  1,  3,  3, 16,
       16, 14,  0,  3,  3,  7, 16,  1, 10, 17, 17,  1,  9,  3, 14,  1,  1,
        4,  1, 16, 17, 17, 16,  1,  3, 16,  1, 19,  4, 16,  1,  5, 19, 16,
        3, 16,  3,  1,  4,  6,  4,  1,  1,  9,  3, 17,  6,  8,  3,  1, 10,
        1,  1,  1,  5, 16, 17,  1,  2, 16,  3, 10,  3,  1,  6,  3,  0,  6,
       18, 16, 16, 10,  3,  8,  4, 16,  1,  2, 16,  8, 17, 14, 16,  8,  9,
        3,  5,  8,  3,  3, 16,  3,  3, 16,  3, 18, 16,  0,  1, 17, 16, 16,
        1,  1, 18,  1, 19,  3,  1, 17, 16,  1, 16,  1, 14, 17, 16, 16,  1,
        3,  3,  3, 19, 19, 19, 16, 16, 12,  1,  1, 19, 13,  4,  6, 16, 12,
       16,  1, 17,  1,  1,  1, 19,  1, 16,  1, 17, 16,  1,  1,  4, 16, 19,
        2, 19,  3,  1, 16,  1, 16, 12,  2,  2, 12,  2, 16,  3, 12,  0,  2,
        1,  1,  2, 19, 19,  1, 12,  2,  1,  2,  2, 12,  2,  3,  0, 16, 16,
        3,  6,  2,  3,  1,  3,  2,  3,  3,  6, 11, 13,  1,  1, 16, 11,  1,
       16,  1,  6, 11,  3

In [97]:
from sklearn.model_selection import GroupKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
groups = np.array([0, 0, 2, 3])
group_kfold = GroupKFold(n_splits=3)
group_kfold.get_n_splits(X, y, groups)

3

In [98]:
for x,y in group_kfold.split(X, y, groups):
    print(x,y)

[2 3] [0 1]
[0 1 2] [3]
[0 1 3] [2]
